import * as Localization from 'expo-localization';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      newConversation: 'New conversation',
      searchConversations: 'Search conversations...',
      deleteConversation: 'Delete Conversation',
      deleteConfirm: 'Are you sure you want to delete this conversation?',
      cancel: 'Cancel',
      delete: 'Delete',
      copy: 'Copy',
      share: 'Share',
      copied: 'Copied to clipboard',
      loading: 'Loading...',
      searchMessages: 'Search messages...',
      islamqaAI: 'IslamQA AI',
      apiErrorMessage: 'Sorry, I could not process your request.',
      promptPlaceholder: 'Type your question...',
      copyMessageOptions: 'Message options',
      showPrivacyForm: 'Privacy Settings',
      privacyChanged: 'Privacy Settings changed succesfully',
      updateAvailable: 'Update Available',
      updateAvailableMessage:
        'A new version of the app is available. Please update to continue using the app.',
      updateNow: 'Update Now',
      removeAds: 'Remove Ads',

      loadingState0: 'Processing your question...',
      loadingState1: 'Finding similar questions...',
      loadingState2: 'This is taking longer than usual',
      loadingState2Subtext:
        'Please bear with us while we generate the best answer...',

      report: 'Report',
      provideFeedback: 'Provide feedback',
      feedbackPlaceholder:
        'What was the issue with the response? How could it be improved?',
      harmfulContent: 'This is harmful/unsafe',
      incorrectContent: "This isn't true",
      unhelpfulContent: "This isn't helpful",
      submit: 'Submit',
      reportSubmitted: 'Report submitted successfully',
      initialMessage: `Welcome! I'm a Muslim scholar specialized in answering religious questions and providing fatwas. I can help you with the following areas:

🕌 Beliefs and monotheism
🤲 Worship and purification
💰 Financial transactions
📖 Legal rulings
🤝 Ethics and manners
👪 Family affairs and marriage
📖 Quran and Hadith interpretation
🤔 And other Islamic topics

Feel free to ask your question, and I'll search the approved fatwas to provide you with the appropriate answer according to Islamic law.

⚠️ Warning: Responses are generated by AI and may contain inaccuracies.`,
    },
  },
  ar: {
    translation: {
      newConversation: 'محادثة جديدة',
      searchConversations: 'ابحث في المحادثات...',
      deleteConversation: 'حذف المحادثة',
      deleteConfirm: 'هل أنت متأكد أنك تريد حذف هذه المحادثة؟',
      cancel: 'إلغاء',
      delete: 'حذف',
      copy: 'نسخ',
      share: 'مشاركة',
      copied: 'تم النسخ إلى الحافظة',
      loading: 'انتظر لحظة...',
      searchMessages: 'ابحث في الرسائل...',
      islamqaAI: 'الإسلام سؤال وجواب AI',
      apiErrorMessage: 'عذرًا، لم أتمكن من معالجة طلبك.',
      promptPlaceholder: 'اكتب سؤالك...',
      copyMessageOptions: 'خيارات الرسالة',
      showPrivacyForm: 'إعدادات الخصوصية',
      privacyChanged: 'تم تغيير إعدادات الخصوصية بنجاح',
      updateAvailable: 'يوجد تحديث',
      updateAvailableMessage:
        'يتوفر إصدار جديد من التطبيق. يرجى التحديث لمواصلة استخدام التطبيق.',
      updateNow: 'قم بالتحديث الآن',
      removeAds: 'قم بإزالة الإعلانات',

      loadingState0: 'يتم معالجة سؤالك...',
      loadingState1: 'أبحث عن أسئلة مشابهه...',
      loadingState2: 'هذا إستغرق أكتر من المعتاد',
      loadingState2Subtext: 'من فضلك ابقى معي لأجد أفضل إجابة...',

      report: 'إبلاغ',
      provideFeedback: 'تقديم ملاحظات',
      feedbackPlaceholder: 'ما هي المشكلة في الرد؟ كيف يمكن تحسينه؟',
      harmfulContent: 'هذا محتوى ضار/غير آمن',
      incorrectContent: 'هذا غير صحيح',
      unhelpfulContent: 'هذا غير مفيد',
      submit: 'إرسال',
      reportSubmitted: 'تم إرسال التقرير بنجاح',
      initialMessage: `مرحباً بك! أنا شيخ مسلم متخصص في الإجابة على الأسئلة الدينية وتقديم الفتاوى. يمكنني مساعدتك في المجالات التالية:

🕌 العقيدة والتوحيد
🤲 العبادات والطهارة
💰 المعاملات المالية
📖 الأحكام الشرعية
🤝 الأخلاق والآداب
👪 شؤون الأسرة والزواج
📖 تفسير القرآن والحديث
🤔 وغيرها من المواضيع الإسلامية

تفضل بطرح سؤالك، وسأبحث في الفتاوى المعتمدة لأقدم لك الإجابة المناسبة وفق الشريعة الإسلامية.

⚠️ تحذير: الردود مولّدة بواسطة الذكاء الاصطناعي وقد تحتوي على أخطاء.
`,
    },
  },
};

i18n.use(initReactI18next).init({
  compatibilityJSON: 'v4',
  resources,
  lng: 'ar',
  fallbackLng: 'ar',
  interpolation: {
    escapeValue: false,
  },
});

export const changeLanguage = (lang: 'ar' | 'en') => {
  i18n.changeLanguage(lang);
};
export const init = () => {};

export default i18n;
